//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using TrackableEntities;
    
    [JsonObject(IsReference = true)]
    [DataContract]
    public partial class AdjustmentVoucher : ITrackable
    {
        public AdjustmentVoucher()
        {
            this.AdjustmentDetail = new List<AdjustmentDetail>();
        }
    
        [DataMember]
        public string AdjID { get; set; }
        [DataMember]
        public Nullable<System.DateTime> Date { get; set; }
        [DataMember]
        public Nullable<int> ReportedBy { get; set; }
        [DataMember]
        public Nullable<int> ApprovedBy { get; set; }
        [DataMember]
        public string Status { get; set; }
        [DataMember]
        public Nullable<double> TotalAmt { get; set; }
    
        
        public ICollection<AdjustmentDetail> AdjustmentDetail { get; set; }
        
        public Employee Employee { get; set; }
        
        public Employee Employee1 { get; set; }
    
        public TrackingState TrackingState { get; set; }
        public ICollection<string> ModifiedProperties { get; set; }
        private Guid EntityIdentifier { get; set; }
    }
}
