//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using TrackableEntities;
    
    [JsonObject(IsReference = true)]
    [DataContract(IsReference = true, Namespace = "http://schemas.datacontract.org/2004/07/TrackableEntities.Models")]
    public partial class AdjustmentDetail : ITrackable
    {
        [DataMember]
        public int AdjSN { get; set; }
        [DataMember]
        public string AdjID { get; set; }
        [DataMember]
        public string ItemID { get; set; }
        [DataMember]
        public Nullable<int> Qty { get; set; }
        [DataMember]
        public Nullable<double> Price { get; set; }
        [DataMember]
        public string Reason { get; set; }
        [DataMember]
        public string Remark { get; set; }
    
        [DataMember]
        public AdjustmentVoucher AdjustmentVoucher { get; set; }
        [DataMember]
        public Item Item { get; set; }
    
        [DataMember]
        public TrackingState TrackingState { get; set; }
        [DataMember]
        public ICollection<string> ModifiedProperties { get; set; }
        [JsonProperty, DataMember]
        private Guid EntityIdentifier { get; set; }
    }
}
