//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using TrackableEntities;
    
    [JsonObject(IsReference = true)]
    [DataContract]
    public partial class Disbursement : ITrackable
    {
        public Disbursement()
        {
            this.DisbursementDetail = new List<DisbursementDetail>();
            this.Requisition = new List<Requisition>();
        }
    
        [DataMember]
        public int DisID { get; set; }
        [DataMember]
        public Nullable<System.DateTime> Date { get; set; }
        [DataMember]
        public Nullable<int> EmpID { get; set; }
        [DataMember]
        public string DeptID { get; set; }
        [DataMember]
        public Nullable<int> CPID { get; set; }
        [DataMember]
        public Nullable<int> ReceivedBy { get; set; }
        [DataMember]
        public string Status { get; set; }
    
        
        public CollectionPoint CollectionPoint { get; set; }
        
        public Department Department { get; set; }
        
        public Employee Employee { get; set; }
        
        public Employee Employee1 { get; set; }
        
        public ICollection<DisbursementDetail> DisbursementDetail { get; set; }
        
        public ICollection<Requisition> Requisition { get; set; }
    
        public TrackingState TrackingState { get; set; }
        public ICollection<string> ModifiedProperties { get; set; }
        private Guid EntityIdentifier { get; set; }
    }
}
