//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using TrackableEntities;
    
    [JsonObject(IsReference = true)]
    [DataContract(IsReference = true, Namespace = "http://schemas.datacontract.org/2004/07/TrackableEntities.Models")]
    public partial class Disbursement : ITrackable
    {
        public Disbursement()
        {
            this.DisbursementDetail = new List<DisbursementDetail>();
            this.Requisition = new List<Requisition>();
        }
    
        [DataMember]
        public string DisID { get; set; }
        [DataMember]
        public Nullable<System.DateTime> Date { get; set; }
        [DataMember]
        public string EmpID { get; set; }
        [DataMember]
        public string DeptID { get; set; }
        [DataMember]
        public string CPID { get; set; }
        [DataMember]
        public string ReceivedBy { get; set; }
        [DataMember]
        public string Status { get; set; }
    
        [DataMember]
        public ICollection<DisbursementDetail> DisbursementDetail { get; set; }
        [DataMember]
        public ICollection<Requisition> Requisition { get; set; }
    
        [DataMember]
        public TrackingState TrackingState { get; set; }
        [DataMember]
        public ICollection<string> ModifiedProperties { get; set; }
        [JsonProperty, DataMember]
        private Guid EntityIdentifier { get; set; }
    }
}
