//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using TrackableEntities;
    
    [JsonObject(IsReference = true)]
    [DataContract(IsReference = true, Namespace = "http://schemas.datacontract.org/2004/07/TrackableEntities.Models")]
    public partial class Employee : ITrackable
    {
        public Employee()
        {
            this.AdjustmentVoucher = new List<AdjustmentVoucher>();
            this.AdjustmentVoucher1 = new List<AdjustmentVoucher>();
            this.CartItems = new List<CartItems>();
            this.Delegate = new List<Delegate>();
            this.MobileNotification = new List<MobileNotification>();
            this.Notification = new List<Notification>();
            this.PurchaseOrder = new List<PurchaseOrder>();
            this.Requisition = new List<Requisition>();
            this.Retrieval = new List<Retrieval>();
        }
    
        [DataMember]
        public string EmpID { get; set; }
        [DataMember]
        public string EmpName { get; set; }
        [DataMember]
        public string DeptID { get; set; }
        [DataMember]
        public string RoleID { get; set; }
        [DataMember]
        public string Contact { get; set; }
        [DataMember]
        public string Email { get; set; }
        [DataMember]
        public string Password { get; set; }
    
        [DataMember]
        public ICollection<AdjustmentVoucher> AdjustmentVoucher { get; set; }
        [DataMember]
        public ICollection<AdjustmentVoucher> AdjustmentVoucher1 { get; set; }
        [DataMember]
        public ICollection<CartItems> CartItems { get; set; }
        [DataMember]
        public ICollection<Delegate> Delegate { get; set; }
        [DataMember]
        public Role Role { get; set; }
        [DataMember]
        public ICollection<MobileNotification> MobileNotification { get; set; }
        [DataMember]
        public ICollection<Notification> Notification { get; set; }
        [DataMember]
        public ICollection<PurchaseOrder> PurchaseOrder { get; set; }
        [DataMember]
        public ICollection<Requisition> Requisition { get; set; }
        [DataMember]
        public ICollection<Retrieval> Retrieval { get; set; }
    
        [DataMember]
        public TrackingState TrackingState { get; set; }
        [DataMember]
        public ICollection<string> ModifiedProperties { get; set; }
        [JsonProperty, DataMember]
        private Guid EntityIdentifier { get; set; }
    }
}
