//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using TrackableEntities;
    
    [JsonObject(IsReference = true)]
    [DataContract]
    public partial class Employee : ITrackable
    {
        public Employee()
        {
            this.AdjustmentVoucher = new List<AdjustmentVoucher>();
            this.AdjustmentVoucher1 = new List<AdjustmentVoucher>();
            this.CartItems = new List<CartItems>();
            this.Delegate = new List<Delegate>();
            this.Department = new List<Department>();
            this.Department1 = new List<Department>();
            this.Department2 = new List<Department>();
            this.Disbursement = new List<Disbursement>();
            this.Disbursement1 = new List<Disbursement>();
            this.MobileNotification = new List<MobileNotification>();
            this.Notification = new List<Notification>();
            this.PurchaseOrder = new List<PurchaseOrder>();
            this.Report = new List<Report>();
            this.Requisition = new List<Requisition>();
            this.Requisition1 = new List<Requisition>();
            this.Requisition2 = new List<Requisition>();
            this.Retrieval = new List<Retrieval>();
        }
    
        [DataMember]
        public int EmpID { get; set; }
        [DataMember]
        public string EmpName { get; set; }
        [DataMember]
        public string DeptID { get; set; }
        [DataMember]
        public string RoleID { get; set; }
        [DataMember]
        public Nullable<int> Phone { get; set; }
        [DataMember]
        public string Email { get; set; }
        [DataMember]
        public string Password { get; set; }
    
         
        public ICollection<AdjustmentVoucher> AdjustmentVoucher { get; set; }
         
        public ICollection<AdjustmentVoucher> AdjustmentVoucher1 { get; set; }
         
        public ICollection<CartItems> CartItems { get; set; }
         
        public ICollection<Delegate> Delegate { get; set; }
         
        public ICollection<Department> Department { get; set; }
         
        public ICollection<Department> Department1 { get; set; }
         
        public ICollection<Department> Department2 { get; set; }
         
        public Department Department3 { get; set; }
         
        public ICollection<Disbursement> Disbursement { get; set; }
         
        public ICollection<Disbursement> Disbursement1 { get; set; }
         
        public Role Role { get; set; }
         
        public ICollection<MobileNotification> MobileNotification { get; set; }
         
        public ICollection<Notification> Notification { get; set; }
         
        public ICollection<PurchaseOrder> PurchaseOrder { get; set; }
         
        public ICollection<Report> Report { get; set; }
         
        public ICollection<Requisition> Requisition { get; set; }
         
        public ICollection<Requisition> Requisition1 { get; set; }
         
        public ICollection<Requisition> Requisition2 { get; set; }
         
        public ICollection<Retrieval> Retrieval { get; set; }
    
         
        public TrackingState TrackingState { get; set; }
         
        public ICollection<string> ModifiedProperties { get; set; }
         
        private Guid EntityIdentifier { get; set; }
    }
}
