//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LogicUniversityEntitie : DbContext
    {
        static LogicUniversityEntitie()
        {
            Database.SetInitializer(new NullDatabaseInitializer<LogicUniversityEntitie>());
        }
    
        public LogicUniversityEntitie()
            : base("name=LogicUniversityEntitie")
        {
    		Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdjustmentDetail> AdjustmentDetail { get; set; }
        public virtual DbSet<AdjustmentVoucher> AdjustmentVoucher { get; set; }
        public virtual DbSet<CartItems> CartItems { get; set; }
        public virtual DbSet<CollectionPoint> CollectionPoint { get; set; }
        public virtual DbSet<Delegate> Delegate { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Disbursement> Disbursement { get; set; }
        public virtual DbSet<DisbursementDetail> DisbursementDetail { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<ItemCategory> ItemCategory { get; set; }
        public virtual DbSet<ItemPrice> ItemPrice { get; set; }
        public virtual DbSet<MobileNotification> MobileNotification { get; set; }
        public virtual DbSet<Notification> Notification { get; set; }
        public virtual DbSet<Priority> Priority { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrder { get; set; }
        public virtual DbSet<PurchaseOrderDetail> PurchaseOrderDetail { get; set; }
        public virtual DbSet<Report> Report { get; set; }
        public virtual DbSet<Requisition> Requisition { get; set; }
        public virtual DbSet<RequisitionDetail> RequisitionDetail { get; set; }
        public virtual DbSet<Retrieval> Retrieval { get; set; }
        public virtual DbSet<RetrievalDetail> RetrievalDetail { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<StockCard> StockCard { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
