//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using TrackableEntities;
    
    [JsonObject(IsReference = true)]
    [DataContract]
    public partial class Priority : ITrackable
    {
        public Priority()
        {
            this.Requisition = new List<Requisition>();
        }
    
        [DataMember]
        public int PriorityID { get; set; }
        [DataMember]
        public string PriorityName { get; set; }
    
         
        public ICollection<Requisition> Requisition { get; set; }
    
         
        public TrackingState TrackingState { get; set; }
         
        public ICollection<string> ModifiedProperties { get; set; }
         
        private Guid EntityIdentifier { get; set; }
    }
}
