//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using TrackableEntities;
    
    [JsonObject(IsReference = true)]
    [DataContract]
    public partial class RequisitionAnalytics : ITrackable
    {
        [DataMember]
        public Nullable<System.DateTime> Date { get; set; }
        [DataMember]
        public string DeptID { get; set; }
        [DataMember]
        public Nullable<int> ItemCatID { get; set; }
        [DataMember]
        public string ItemID { get; set; }
        [DataMember]
        public Nullable<int> RequestQty { get; set; }
        [DataMember]
        public Nullable<int> IssueQty { get; set; }
        [DataMember]
        public int ReqID { get; set; }
        [DataMember]
        public Nullable<double> Price { get; set; }
    
        public TrackingState TrackingState { get; set; }
        public ICollection<string> ModifiedProperties { get; set; }
        private Guid EntityIdentifier { get; set; }
    }
}
