//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using TrackableEntities;
    
    [JsonObject(IsReference = true)]
    [DataContract]
    public partial class Requisition : ITrackable
    {
        public Requisition()
        {
            this.RequisitionDetail = new List<RequisitionDetail>();
        }
    
        [DataMember]
        public int ReqID { get; set; }
        [DataMember]
        public Nullable<int> DisID { get; set; }
        [DataMember]
        public Nullable<int> RetID { get; set; }
        [DataMember]
        public Nullable<int> EmpID { get; set; }
        [DataMember]
        public string DeptID { get; set; }
        [DataMember]
        public Nullable<System.DateTime> Date { get; set; }
        [DataMember]
        public Nullable<int> PriorityID { get; set; }
        [DataMember]
        public string PRemark { get; set; }
        [DataMember]
        public Nullable<int> StatusID { get; set; }
        [DataMember]
        public Nullable<int> HandledBy { get; set; }
        [DataMember]
        public string Remark { get; set; }
        [DataMember]
        public Nullable<int> ReceivedBy { get; set; }
    
         
        public Department Department { get; set; }
         
        public Disbursement Disbursement { get; set; }
         
        public Employee Employee { get; set; }
         
        public Employee Employee1 { get; set; }
         
        public Employee Employee2 { get; set; }
         
        public Priority Priority { get; set; }
         
        public Retrieval Retrieval { get; set; }
         
        public Status Status { get; set; }
         
        public ICollection<RequisitionDetail> RequisitionDetail { get; set; }
    
         
        public TrackingState TrackingState { get; set; }
         
        public ICollection<string> ModifiedProperties { get; set; }
         
        private Guid EntityIdentifier { get; set; }
    }
}
