//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using TrackableEntities;
    
    [JsonObject(IsReference = true)]
    [DataContract(IsReference = true, Namespace = "http://schemas.datacontract.org/2004/07/TrackableEntities.Models")]
    public partial class Requisition : ITrackable
    {
        public Requisition()
        {
            this.RequisitionDetail = new List<RequisitionDetail>();
        }
    
        [DataMember]
        public string ReqID { get; set; }
        [DataMember]
        public string DisID { get; set; }
        [DataMember]
        public string RetID { get; set; }
        [DataMember]
        public string EmpID { get; set; }
        [DataMember]
        public string DeptID { get; set; }
        [DataMember]
        public Nullable<System.DateTime> Date { get; set; }
        [DataMember]
        public Nullable<int> PriorityID { get; set; }
        [DataMember]
        public string PRemark { get; set; }
        [DataMember]
        public Nullable<int> StatusID { get; set; }
        [DataMember]
        public string HandledBy { get; set; }
        [DataMember]
        public string Remark { get; set; }
        [DataMember]
        public string ReceivedBy { get; set; }
    
        [DataMember]
        public Department Department { get; set; }
        [DataMember]
        public Disbursement Disbursement { get; set; }
        [DataMember]
        public Employee Employee { get; set; }
        [DataMember]
        public Priority Priority { get; set; }
        [DataMember]
        public Status Status { get; set; }
        [DataMember]
        public ICollection<RequisitionDetail> RequisitionDetail { get; set; }
    
        [DataMember]
        public TrackingState TrackingState { get; set; }
        [DataMember]
        public ICollection<string> ModifiedProperties { get; set; }
        [JsonProperty, DataMember]
        private Guid EntityIdentifier { get; set; }
    }
}
