//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using TrackableEntities;
    
    [JsonObject(IsReference = true)]
    [DataContract(IsReference = true, Namespace = "http://schemas.datacontract.org/2004/07/TrackableEntities.Models")]
    public partial class Supplier : ITrackable
    {
        public Supplier()
        {
            this.ItemPrice = new List<ItemPrice>();
            this.PurchaseOrder = new List<PurchaseOrder>();
        }
    
        [DataMember]
        public string SupplierID { get; set; }
        [DataMember]
        public string SupplierName { get; set; }
        [DataMember]
        public string Contact { get; set; }
        [DataMember]
        public Nullable<int> RegNo { get; set; }
        [DataMember]
        public string Phone { get; set; }
        [DataMember]
        public string Address { get; set; }
        [DataMember]
        public string Fax { get; set; }
        [DataMember]
        public string Rank { get; set; }
    
        [DataMember]
        public ICollection<ItemPrice> ItemPrice { get; set; }
        [DataMember]
        public ICollection<PurchaseOrder> PurchaseOrder { get; set; }
    
        [DataMember]
        public TrackingState TrackingState { get; set; }
        [DataMember]
        public ICollection<string> ModifiedProperties { get; set; }
        [JsonProperty, DataMember]
        private Guid EntityIdentifier { get; set; }
    }
}
